// web/src/components/chat/ChatMessageComponent.vue
<script setup lang="ts">
import { computed } from "vue"
import MarkdownRender from "markstream-vue"

import AttachmentComponent from "@/components/AttachmentComponent.vue"
import type { ThreadMessageAttachmentResponse } from "@/types/attachment"
import type { ChatMessage } from "@/types/chat"

const props = defineProps<{
  message: ChatMessage
}>()

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null

const isAttachment = (
  value: unknown
): value is ThreadMessageAttachmentResponse =>
  isRecord(value) && typeof value.file_id === "string"

const event = computed(() =>
  isRecord(props.message.payload.event)
    ? props.message.payload.event
    : {}
)
const content = computed(() =>
  typeof event.value.content === "string" ? event.value.content : ""
)
const attachments = computed(() =>
  Array.isArray(event.value.attachments)
    ? event.value.attachments.filter(isAttachment)
    : []
)
const isAiText = computed(
  () => props.message.type === "ai" && props.message.payload.type === "text"
)
const isAiTool = computed(
  () => props.message.type === "ai" && props.message.payload.type === "tool"
)
const isFinal = computed(() => event.value.status !== "streaming")
const toolName = computed(() =>
  typeof event.value.name === "string" ? event.value.name : "tool"
)
</script>

<template>
  <article
    v-if="message.type === 'human'"
    class="flex justify-end"
  >
    <div
      class="max-w-[min(82%,42rem)] rounded-[1.15rem] bg-mist px-4 py-2.5 text-graphite"
    >
      <p
        v-if="content"
        class="m-0 whitespace-pre-wrap leading-7"
      >
        {{ content }}
      </p>

      <ul
        v-if="attachments.length"
        class="m-0 flex list-none flex-wrap gap-2 p-0"
        :class="{ 'mt-3': content }"
      >
        <AttachmentComponent
          v-for="attachment in attachments"
          :key="attachment.file_id"
          :attachment="attachment"
        />
      </ul>
    </div>
  </article>

  <article
    v-else-if="isAiText"
    class="min-w-0 max-w-full leading-7 text-graphite"
  >
    <MarkdownRender
      v-if="content"
      mode="chat"
      :content="content"
      :final="isFinal"
    />

    <ul
      v-if="attachments.length"
      class="m-0 flex list-none flex-wrap gap-2 p-0"
      :class="{ 'mt-3': content }"
    >
      <AttachmentComponent
        v-for="attachment in attachments"
        :key="attachment.file_id"
        :attachment="attachment"
      />
    </ul>
  </article>

  <article
    v-else-if="isAiTool"
    class="w-fit max-w-full rounded-lg border border-graphite/10 bg-graphite/[0.025] px-3 py-2 text-sm text-slate"
  >
    <div class="flex items-center gap-2">
      <span class="rounded bg-graphite/7 px-1.5 py-0.5 text-xs font-medium text-graphite">
        Tool
      </span>
      <span class="font-mono text-xs">{{ toolName }}</span>
    </div>
    <p class="mt-1 mb-0 text-xs">Agent state updated</p>
  </article>

  <article v-else class="whitespace-pre-wrap text-sm text-slate">
    {{ content }}
  </article>
</template>

// web/src/pages/chat/components/ChatMessage.tsx
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import type { ThreadMessageAttachmentResponse } from "@/types/attachment";
import type { ChatMessage as ChatMessageType } from "@/types/chat";
import { Attachment } from "@/pages/chat/components/Attachment";

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null;
const isAttachment = (
  value: unknown,
): value is ThreadMessageAttachmentResponse =>
  isRecord(value) && typeof value.file_id === "string";

function AgentTasks({ event }: { event: Record<string, unknown> }) {
  const state = isRecord(event.agent_state) ? event.agent_state : {};
  const todos = Array.isArray(state.agent_todo)
    ? state.agent_todo.filter(
        (item): item is { content: string; status: string } =>
          isRecord(item) &&
          typeof item.content === "string" &&
          ["pending", "in_progress", "completed"].includes(String(item.status)),
      )
    : [];
  if (!todos.length) return null;
  return (
    <details open className="w-full max-w-2xl text-sm">
      <summary className="cursor-pointer py-1 text-xs text-slate">
        {todos.length} {todos.length === 1 ? "task" : "tasks"} ·{" "}
        {todos.filter((item) => item.status === "completed").length} completed
      </summary>
      <div className="mt-1.5 grid gap-1">
        {todos.map((todo, index) => (
          <details key={`${todo.content}-${index}`}>
            <summary className="cursor-pointer rounded-md px-1 py-1 text-xs hover:bg-mist">
              <span className="font-medium">
                {todo.status === "in_progress"
                  ? "In progress"
                  : todo.status === "completed"
                    ? "Completed"
                    : "Pending"}
              </span>
              <span className="ml-2 text-slate">{todo.content}</span>
            </summary>
            <pre className="ml-4 overflow-x-auto border-l border-graphite/10 py-1 pl-3 text-[11.5px] text-slate">
              {JSON.stringify(todo, null, 2)}
            </pre>
          </details>
        ))}
      </div>
    </details>
  );
}

export function ChatMessage({ message }: { message: ChatMessageType }) {
  const event = isRecord(message.payload.event) ? message.payload.event : {};
  const content = typeof event.content === "string" ? event.content : "";
  const attachments = Array.isArray(event.attachments)
    ? event.attachments.filter(isAttachment)
    : [];
  if (message.type === "human")
    return (
      <article className="flex justify-end">
        <div className="max-w-[min(82%,42rem)] rounded-[1.15rem] bg-mist px-4 py-2.5 text-graphite">
          {content && (
            <p className="m-0 whitespace-pre-wrap leading-7">{content}</p>
          )}
          {attachments.length > 0 && (
            <ul
              className={`m-0 flex list-none flex-wrap gap-2 p-0 ${content ? "mt-3" : ""}`}
            >
              {attachments.map((item) => (
                <Attachment key={item.file_id} attachment={item} />
              ))}
            </ul>
          )}
        </div>
      </article>
    );
  if (message.payload.type === "tool") return <AgentTasks event={event} />;
  return (
    <article className="min-w-0 max-w-full leading-7 text-graphite">
      {content && (
        <div className="chat-markdown max-w-none">
          <ReactMarkdown remarkPlugins={[remarkGfm]}>{content}</ReactMarkdown>
        </div>
      )}
      {attachments.length > 0 && (
        <ul className="mt-3 flex list-none flex-wrap gap-2 p-0">
          {attachments.map((item) => (
            <Attachment key={item.file_id} attachment={item} />
          ))}
        </ul>
      )}
    </article>
  );
}
