// web/src/pages/chat/components/Attachment.tsx
import { File as FileIcon, X } from "lucide-react";
import { Tooltip } from "antd";
import type { ChatAttachment } from "@/types/attachment";

export function Attachment({
  attachment,
  remove,
}: {
  attachment: ChatAttachment;
  remove?: (id: string) => void;
}) {
  return (
    <li
      className={`grid h-11 max-w-[17rem] min-w-0 shrink-0 items-center gap-2 rounded-full border border-graphite/12 bg-paper p-1 text-graphite ${remove ? "grid-cols-[2rem_minmax(0,1fr)_2rem]" : "grid-cols-[2rem_minmax(0,1fr)] pr-3"}`}
    >
      <span
        className="grid size-8 place-items-center overflow-hidden rounded-full bg-graphite/6 text-slate"
        aria-hidden="true"
      >
        {attachment.content_type.startsWith("image/") &&
        attachment.access_url ? (
          <img
            src={attachment.access_url}
            alt=""
            className="size-full object-cover"
          />
        ) : (
          <FileIcon size={15} />
        )}
      </span>
      <strong
        className="min-w-0 truncate text-sm font-medium"
        title={attachment.file_name}
      >
        {attachment.file_name}
      </strong>
      {remove && (
        <Tooltip title={`Remove ${attachment.file_name}`}>
          <button
            type="button"
            className="grid size-7 place-items-center rounded-full text-graphite/58 hover:bg-graphite hover:text-paper"
            aria-label={`Remove attachment ${attachment.file_name}`}
            onClick={() => remove(attachment.file_id)}
          >
            <X size={14} />
          </button>
        </Tooltip>
      )}
    </li>
  );
}

// web/src/components/AttachmentComponent.vue
<script setup lang="ts">
import { computed } from "vue"
import { File as FileIcon, X } from "@lucide/vue"

import type { ChatAttachment } from "@/types/attachment"

const props = defineProps<{
  attachment: ChatAttachment
  removable?: boolean
}>()

const emit = defineEmits<{
  remove: [fileId: string]
}>()

const isImage = computed(() =>
  props.attachment.content_type.startsWith("image/") &&
  Boolean(props.attachment.access_url)
)
</script>

<template>
  <li
    class="grid h-11 max-w-[17rem] min-w-0 shrink-0 items-center gap-2 rounded-full border border-graphite/12 bg-paper p-1 text-graphite"
    :class="removable
      ? 'grid-cols-[2rem_minmax(0,1fr)_2rem]'
      : 'grid-cols-[2rem_minmax(0,1fr)] pr-3'"
  >
    <span
      class="grid size-8 shrink-0 place-items-center overflow-hidden rounded-full bg-graphite/6 text-slate"
      aria-hidden="true"
    >
      <img
        v-if="isImage"
        class="size-full object-cover"
        :src="props.attachment.access_url ?? undefined"
        alt=""
      >
      <FileIcon
        v-else
        :size="15"
        :stroke-width="1.8"
      />
    </span>

    <strong
      class="min-w-0 truncate font-medium text-sm"
      :title="props.attachment.file_name"
    >
      {{ props.attachment.file_name }}
    </strong>

    <button
      v-if="removable"
      class="grid size-7 shrink-0 place-items-center rounded-full bg-transparent text-graphite/58 transition-colors duration-120 hover:bg-graphite hover:text-paper motion-reduce:transition-none"
      type="button"
      :aria-label="`Remove attachment ${props.attachment.file_name}`"
      :title="`Remove ${props.attachment.file_name}`"
      @click="emit('remove', props.attachment.file_id)"
    >
      <X
        :size="14"
        :stroke-width="1.9"
        aria-hidden="true"
      />
    </button>
  </li>
</template>
